"""Backend-neutral randomization planning and candidate-generator helpers.

The module deliberately knows nothing about MuJoCo or a particular simulator.
Backends provide pose reads/writes and constraint evaluation; this module owns
the stable action graph and deterministic candidate-generation semantics.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, List, Mapping, Sequence, Set, Tuple

import numpy as np
from scipy.spatial.distance import cdist
from scipy.stats import qmc

from .framework import (
    OperatorRandomizationConfig,
    RandomizationGeneratorConfig,
    RandomizationGeneratorInput,
    RandomizationGeneratorKind,
    RandomizationInput,
    RandomizationPoissonDiskConfig,
    RandomizationReference,
    RandomizationSpec,
    canonical_randomization_spec,
)


@dataclass(frozen=True)
class RandomizationAction:
    """One independently sampled object, operator, or operator-attribute pose."""

    kind: str
    owner: str
    label: str
    randomization: RandomizationSpec


@dataclass(frozen=True)
class RandomizationPlan:
    """Compiled action graph used by a backend reset."""

    actions: Mapping[str, RandomizationAction]
    dependencies: Mapping[str, frozenset[str]]
    order: Tuple[str, ...]
    components: Tuple[Tuple[str, ...], ...]


class RandomizationFailureError(RuntimeError):
    """Raised when a constrained randomization cannot produce a candidate."""

    def __init__(
        self,
        *,
        target: str,
        attempts: int,
        violations: Sequence[str],
        minimum_clearance: float,
    ) -> None:
        self.target = target
        self.attempts = int(attempts)
        self.violations = tuple(str(value) for value in violations)
        self.minimum_clearance = float(minimum_clearance)
        detail = ", ".join(self.violations) or "unknown constraint"
        super().__init__(
            f"Randomization for '{target}' failed after {attempts} attempts: "
            f"{detail}; minimum_clearance={minimum_clearance:.6g}"
        )


class PoissonDiskCandidateStream:
    """Finite candidate pool generated by one SciPy Poisson-disk engine.

    A stream is created for one randomized action and environment during one
    component reset.
    The engine generates the complete pool once, so the returned candidates
    retain SciPy's intra-pool Poisson-disk spacing instead of reinitializing a
    new engine for every attempt.
    """

    def __init__(
        self,
        config: RandomizationPoissonDiskConfig,
        *,
        dimension: int,
        sample_count: int,
        seed: int,
    ) -> None:
        radius = (
            float(config.radius)
            if config.radius is not None
            else 0.5 * max(sample_count, 1) ** (-1.0 / max(dimension, 1))
        )
        kwargs: dict[str, object] = {
            "d": dimension,
            "radius": radius,
            "hypersphere": config.hypersphere,
            "ncandidates": int(config.ncandidates),
            "optimization": config.optimization,
            "rng": seed,
        }
        try:
            engine = qmc.PoissonDisk(**kwargs)
            pool_size = (
                max(sample_count, dimension + 2)
                if config.optimization == "lloyd"
                else sample_count
            )
            self._samples = np.asarray(engine.random(n=pool_size), dtype=np.float64)
        except MemoryError as exc:
            raise ValueError(
                "Poisson-disk radius is too small for the pose dimension; "
                "increase generator.poisson_disk.radius or reduce the pose dimension."
            ) from exc
        except (ValueError, RuntimeError) as exc:
            if config.optimization == "lloyd":
                raise ValueError(
                    "Poisson-disk optimization='lloyd' needs enough points "
                    "for a Voronoi diagram; increase candidate_count or "
                    "reduce generator.poisson_disk.radius."
                ) from exc
            raise
        self._index = 0

    def next(self) -> np.ndarray:
        """Return the next point, preserving the generated pool order."""
        if self._index >= len(self._samples):
            raise ValueError(
                "Poisson-disk candidate pool was exhausted before a feasible "
                "randomization was found; reduce the radius or increase the "
                "available proposal space."
            )
        point = self._samples[self._index]
        self._index += 1
        return point.copy()


def _parse_entity_reference(reference: str) -> tuple[str, str | None]:
    if "." in reference:
        name, attribute = reference.split(".", 1)
        if attribute in {"base", "eef"}:
            return name, attribute
    return reference, None


def _references(spec: RandomizationSpec) -> Iterable[RandomizationReference | str]:
    for region in (
        spec.proposal.regions if hasattr(spec.proposal, "regions") else (spec.proposal,)
    ):
        yield from region.references()


def compile_randomization_plan(
    randomization: Mapping[str, RandomizationInput | OperatorRandomizationConfig],
    *,
    object_names: Set[str],
    operator_names: Set[str],
) -> RandomizationPlan:
    """Compile randomization entries into a deterministic dependency graph."""
    actions: Dict[str, RandomizationAction] = {}
    declaration_order: List[str] = []
    for owner, value in randomization.items():
        if owner in operator_names and isinstance(value, OperatorRandomizationConfig):
            for attribute, kind in (("base", "operator_base"), ("eef", "operator_eef")):
                nested = getattr(value, attribute)
                if nested is None:
                    continue
                label = f"{owner}.{attribute}"
                actions[label] = RandomizationAction(
                    kind=kind,
                    owner=owner,
                    label=label,
                    randomization=canonical_randomization_spec(nested),
                )
                declaration_order.append(label)
            continue
        if owner in object_names:
            actions[owner] = RandomizationAction(
                kind="object",
                owner=owner,
                label=owner,
                randomization=canonical_randomization_spec(value),
            )
            declaration_order.append(owner)

    dependencies: Dict[str, Set[str]] = {label: set() for label in actions}
    for label, action in actions.items():
        if action.kind == "operator_eef" and f"{action.owner}.base" in actions:
            dependencies[label].add(f"{action.owner}.base")
        for reference in _references(action.randomization):
            if isinstance(reference, RandomizationReference):
                continue
            bare, attribute = _parse_entity_reference(reference)
            dependency = f"{bare}.{attribute}" if attribute else bare
            if attribute is None and f"{bare}.base" in actions:
                dependency = f"{bare}.base"
            if dependency in actions:
                dependencies[label].add(dependency)

    declaration_index = {label: index for index, label in enumerate(declaration_order)}
    order: List[str] = []
    visited: Set[str] = set()
    visiting: Set[str] = set()

    def visit(label: str) -> None:
        if label in visited:
            return
        if label in visiting:
            raise ValueError(f"Circular randomization reference involving '{label}'")
        visiting.add(label)
        for dependency in sorted(
            dependencies[label], key=declaration_index.__getitem__
        ):
            visit(dependency)
        visiting.remove(label)
        visited.add(label)
        order.append(label)

    for label in declaration_order:
        visit(label)

    adjacency: Dict[str, Set[str]] = {label: set() for label in actions}
    for label, parents in dependencies.items():
        for parent in parents:
            adjacency[label].add(parent)
            adjacency[parent].add(label)
    # Separation is a joint constraint. Connect all constrained object actions
    # so the backend samples and validates them as one component rather than
    # introducing declaration-order bias.
    separated_objects = [
        label
        for label, action in actions.items()
        if action.kind == "object"
        and action.randomization.constraints.separated is not None
    ]
    if separated_objects:
        anchor = separated_objects[0]
        # A separation declaration defines the joint randomized-object set.
        # Include unconstrained object actions too, so a single declaration
        # protects its target from every other randomized object.
        joint_objects = [
            label for label, action in actions.items() if action.kind == "object"
        ]
        for label in joint_objects[1:]:
            adjacency[anchor].add(label)
            adjacency[label].add(anchor)
    order_index = {label: index for index, label in enumerate(order)}
    components: List[Tuple[str, ...]] = []
    seen: Set[str] = set()
    for label in order:
        if label in seen:
            continue
        stack = [label]
        component: Set[str] = set()
        while stack:
            current = stack.pop()
            if current in seen:
                continue
            seen.add(current)
            component.add(current)
            stack.extend(adjacency[current] - seen)
        components.append(tuple(sorted(component, key=order_index.__getitem__)))

    return RandomizationPlan(
        actions=actions,
        dependencies={
            label: frozenset(values) for label, values in dependencies.items()
        },
        order=tuple(order),
        components=tuple(components),
    )


def unit_candidate(
    *,
    rng: np.random.Generator,
    dimension: int,
    generator: RandomizationGeneratorInput,
    index: int,
    candidate_count: int,
    min_distance: float = 0.0,
    seed: int = 0,
    poisson_stream: PoissonDiskCandidateStream | None = None,
) -> np.ndarray:
    """Return one point from a SciPy QMC generator in ``[0, 1]^dimension``.

    ``PoissonDisk`` is the only parameterized generator at the public
    configuration seam. Its ``radius`` is normalized to the unit cube;
    project-level physical spacing remains ``distribution.min_distance``.
    """
    poisson_config = (
        generator.poisson_disk
        if isinstance(generator, RandomizationGeneratorConfig)
        else None
    )
    generator_kind = (
        RandomizationGeneratorKind.POISSON_DISK
        if poisson_config is not None
        else generator
    )
    if generator_kind == RandomizationGeneratorKind.IID:
        return np.asarray(rng.random(dimension), dtype=np.float64)
    if candidate_count <= 0:
        raise ValueError("candidate_count must be positive")
    if generator_kind == RandomizationGeneratorKind.LATIN_HYPERCUBE:
        engine = qmc.LatinHypercube(d=dimension, seed=seed)
        return np.asarray(
            engine.random(n=candidate_count)[index % candidate_count],
            dtype=np.float64,
        )
    if generator_kind == RandomizationGeneratorKind.HALTON:
        engine = qmc.Halton(d=dimension, scramble=True, seed=seed)
        engine.fast_forward(index)
        return np.asarray(engine.random(n=1)[0], dtype=np.float64)
    if generator_kind == RandomizationGeneratorKind.SOBOL:
        engine = qmc.Sobol(d=dimension, scramble=True, seed=seed)
        engine.fast_forward(index)
        return np.asarray(engine.random(n=1)[0], dtype=np.float64)
    if generator_kind == RandomizationGeneratorKind.POISSON_DISK:
        if poisson_stream is not None:
            return poisson_stream.next()
        radius = (
            float(poisson_config.radius)
            if poisson_config is not None and poisson_config.radius is not None
            else 0.5 * candidate_count ** (-1.0 / max(dimension, 1))
        )
        kwargs: dict[str, object] = {
            "d": dimension,
            "radius": radius,
            "rng": seed,
        }
        if poisson_config is not None:
            kwargs.update(
                hypersphere=poisson_config.hypersphere,
                ncandidates=int(poisson_config.ncandidates),
                optimization=poisson_config.optimization,
            )
        try:
            engine = qmc.PoissonDisk(**kwargs)
        except MemoryError as exc:
            raise ValueError(
                "Poisson-disk radius is too small for the pose dimension; "
                "increase generator.radius or reduce the pose dimension."
            ) from exc
        if poisson_config is not None and poisson_config.optimization == "lloyd":
            # SciPy's Lloyd post-processing needs a non-degenerate sample
            # (and enough points to construct a Voronoi diagram).  Generate
            # a bounded optimized pool, then use the requested stream index.
            # Do not scale this pool with ``index``: reset indices are stream
            # positions and can grow without bound, while the seed already
            # gives each reset a distinct deterministic pool.
            pool_size = max(candidate_count, dimension + 2)
            try:
                sample = engine.random(n=pool_size)
            except (ValueError, RuntimeError) as exc:
                raise ValueError(
                    "Poisson-disk optimization='lloyd' needs enough points "
                    "for a Voronoi diagram; increase candidate_count or "
                    "reduce generator.poisson_disk.radius."
                ) from exc
            if len(sample) == 0:
                raise ValueError("Poisson-disk Lloyd optimization produced no points")
            return np.asarray(sample[index % len(sample)], dtype=np.float64)
        # Poisson-disk streams are finite for a fixed radius.  Rebuilding the
        # SciPy engine per candidate with an index-derived seed avoids relying
        # on ``fast_forward`` to skip past a stream that may already be
        # exhausted (especially in six-dimensional pose spaces).
        sample = engine.random(n=1)
        if len(sample) == 0:
            raise ValueError(
                "Poisson-disk generator could not produce a candidate; "
                "reduce generator.radius or increase the available proposal space."
            )
        return np.asarray(sample[0], dtype=np.float64)
    raise ValueError(f"Unsupported randomization generator: {generator_kind!r}")


def maximin_select(
    candidates: np.ndarray,
    *,
    count: int,
    min_distance: float = 0.0,
    seed_points: np.ndarray | None = None,
) -> np.ndarray:
    """Select a deterministic maximin subset from candidate points.

    The first point is the candidate with the smallest lexicographic index;
    subsequent points maximize distance to the selected set. A positive
    ``min_distance`` filters candidates that cannot satisfy the requested
    spacing. ``seed_points`` is an optional low-level scoring anchor; the
    backend's public selector contract keeps cross-reset history outside this
    helper. Backends may transform poses or use a different physical distance
    metric before calling it.
    """
    points = np.asarray(candidates, dtype=np.float64)
    if points.ndim != 2:
        raise ValueError("candidates must have shape (N, D)")
    if count <= 0 or len(points) == 0:
        return points[:0]
    seed = None
    if seed_points is not None:
        seed = np.asarray(seed_points, dtype=np.float64)
        if seed.size == 0:
            seed = None
        elif seed.ndim != 2 or seed.shape[1] != points.shape[1]:
            raise ValueError("seed_points must have shape (M, D)")
    if seed is None:
        selected = [0]
    else:
        distances = cdist(points, seed)
        scores = distances.min(axis=1)
        first = int(np.argmax(scores))
        if scores[first] < min_distance:
            return points[:0]
        selected = [first]
    remaining = set(range(len(points))) - set(selected)
    while remaining and len(selected) < count:
        best_index = None
        best_score = -np.inf
        for index in sorted(remaining):
            distance = float(cdist(points[index : index + 1], points[selected]).min())
            if distance < min_distance:
                continue
            if distance > best_score:
                best_score = distance
                best_index = index
        if best_index is None:
            break
        selected.append(best_index)
        remaining.remove(best_index)
    return points[np.asarray(selected, dtype=np.int64)]
